### ISSUE TITLE
External Projects > Refactor admin section 

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/biocollect#91]
* Change the layout of the admin screens to match the layout used by internal projects, with just the "Project Info" and "Membership" options

**Comment by m-r-c** [comment]
*Peer Review*
Just need to update the unit tests to reflect changes in ProjectController.

*Peer Test*
1) No tabs visible on the survey details admin screen:

1. Select an internal CS project
1. Go to the Admin tab
1. Select Survey Settings
1. A survey is selected by default, but no tabs are visible (just the tab headings). Changing the selected survey does not help. You need to click on the tab heading for the tab to be displayed.

2) No selected tab for external admin 

1. Navigate to the Admin tab for an External CS project
1. The Project Info tab is not selected by default: this is selected for Internal CS projects.

**Comment by sat01a** [comment]
Fixed unit test and tab selection issue.

**Comment by m-r-c** [comment]
The second issue isn't fixed (No selected tab for external admin)

**Comment by sat01a** [comment]
There was existing bug with a wrong variable!. Give it a go now.
(I was a fcadmin, that's why I couldn't reproduce it!)

**Comment by m-r-c** [comment]
That last change uncovered a bug with the mapWithFeature.js, which caused the page load to fail. That has been fixed. 

All good now.
